# @package _global_
module:
  _target_: emg2qwerty.lightning.BidirectionalLSTMCTCModule
  in_features: 528
  mlp_features: [384]
  hidden_size: 384   # BiLSTM output = 2*384 = 768, matching LSTM hidden_size
  num_layers: 2
  num_attention_heads: 8   # 768 / 8 = 96 features per head
  dropout: 0.2

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]
